### ISSUE TITLE
Component only works with 2245 hub, not 2242

### ISSUE THREAD

**Issue by andy1441** [home-assistant/home-assistant.io#450]
I don't see any way to make this component work with my existing 2242 hub.  Am I missing something or is the 2242 hub not supported?

**Comment by fabaff** [comment]
What component are you talking about?

**Comment by Landrash** [comment]
My guess would be the Insteon Hub
**2242**-2222 v1. 
**2245**-2222 v2. Adds [API](http://www.insteon.com/developer) support.

Since the [Insteon component](https://home-assistant.io/components/insteon_hub/) requires an API key and the REST API wasn't available until the 2245-2222 version my guess would be a no.

**Comment by andy1441** [comment]
Landrash, I am assuming the same thing.  FYI, OpenHab supports the 2242 hub, so it's not like the 2242 hub is impossible to program.

**Comment by Landrash** [comment]
@andy1441 Well then. There you have your first HA project ;)
